function renderCart(){const units=cart.reduce((a,x)=>a+Number(x.qty||0),0);$('#units').textContent=`${units} u.`;$('#cart').innerHTML=cart.length?cart.map((x,i)=>{const pending=Math.max(0,Number(x.qty)-Number(x.stock_disponible||0));return `<div class="cart-item"><b>${esc(x.descripcion)}</b><div class="meta">${esc(x.sku)} · Stock ${x.stock_disponible} · ${money(x.precio)} + IVA</div><div class="qty"><button data-dec="${i}">−</button><input data-qty="${i}" type="number" min="1" value="${x.qty}"><button data-inc="${i}">+</button><button class="btn danger" data-del="${i}" style="width:auto">Quitar</button></div>${x.manual?`<input data-iobs="${i}" placeholder="Observación de SKU manual" value="${esc(x.observacion_item||'')}">`:''}${pending?`<div class="warn tiny">${pending} unidad/es quedarán pendientes por stock.</div>`:''}</div>`}).join(''):'<div class="muted tiny">Sin artículos todavía.</div>';$('#qtywarn').innerHTML=units&&units<60?'<div class="warn">Pedido menor a 60 unidades. Es advertencia, no bloqueo.</div>':'';calcTotals()}
$('#cart').onclick=e=>{let i;if(e.target.dataset.inc!=null){i=+e.target.dataset.inc;cart[i].qty++}if(e.target.dataset.dec!=null){i=+e.target.dataset.dec;cart[i].qty=Math.max(1,cart[i].qty-1)}if(e.target.dataset.del!=null){i=+e.target.dataset.del;cart.splice(i,1)}renderCart();saveDraft()};
$('#cart').onchange=e=>{if(e.target.dataset.qty!=null){cart[+e.target.dataset.qty].qty=Math.max(1,Number(e.target.value||1))}if(e.target.dataset.iobs!=null){cart[+e.target.dataset.iobs].observacion_item=e.target.value}renderCart();saveDraft()};
function calcTotals(){const s=cart.reduce((a,x)=>a+Number(x.qty)*Number(x.precio),0),p=Math.min(30,Math.max(0,Number($('#discount').value||0))),d=s*p/100,n=s-d,iv=n*.21;$('#sub').textContent=money(s);$('#discAmt').textContent=money(d);$('#net').textContent=money(n);$('#iva').textContent=money(iv);$('#total').textContent=money(n+iv)}
$('#discount').oninput=()=>{calcTotals();saveDraft()};['payment','delivery','transport','obs'].forEach(id=>$('#'+id).addEventListener('change',saveDraft));$('#obs').addEventListener('input',saveDraft);$('#transport').addEventListener('input',saveDraft);$('#delivery').onchange=()=>{toggleTransport();saveDraft()};
function toggleTransport(){$('#transportWrap').classList.toggle('hidden',$('#delivery').value!=='Transporte')}

function openManual(prefill=''){modal('SKU manual',`<div class="warn tiny">Stock inicial 0. No bloquea la confirmación.</div><input id="msku" placeholder="SKU" value="${esc(prefill)}"><input id="mdesc" placeholder="Artículo / descripción"><div class="grid2"><input id="mtype" placeholder="Tipo"><input id="mprod" placeholder="Producto"><input id="mcolor" placeholder="Color"><input id="msize" placeholder="Medida"></div><input id="mprice" type="number" min="0" placeholder="Precio s/IVA"><textarea id="mobs" placeholder="Observación del SKU manual"></textarea><button id="msave" class="btn primary">Crear y agregar</button>`);$('#msave').onclick=async()=>{const sku=$('#msku').value.trim().toUpperCase();if(!sku)return toast('Ingresá SKU');const body={sku,descripcion:$('#mdesc').value.trim()||sku,tipo:$('#mtype').value.trim()||null,producto:$('#mprod').value.trim()||null,color:$('#mcolor').value.trim()||null,medida:$('#msize').value.trim()||null,unidad_venta:'UN',precio:Number($('#mprice').value||0),stock_inicial:0,stock_disponible:0,manual:true,activo:true,observacion_manual:$('#mobs').value.trim()||null};const {data,error}=await sb.from('productos').upsert(body,{onConflict:'sku'}).select().single();if(error)return toast(error.message);closeModal();addProduct({...data,observacion_item:body.observacion_manual||''});loadProducts('')}}
$('#manualBtn').onclick=()=>openManual('');
function openScanner(){if(typeof Html5Qrcode==='undefined')return toast('No se pudo cargar el lector QR.');modal('Escanear producto','<div id="reader" class="scanner"></div><div class="tiny muted" style="margin-top:8px">Al leer el QR vuelve al pedido y deja la cantidad lista para editar.</div>');const qr=new Html5Qrcode('reader');qr.start({facingMode:'environment'},{fps:12,qrbox:{width:240,height:240}},async text=>{try{await qr.stop()}catch{}closeModal();const sku=text.trim();let data=[],error=null;if(navigator.onLine){const r=await sb.from('productos').select('*').ilike('sku',sku).limit(1);data=r.data||[];error=r.error}else{const p=productCache.find(x=>String(x.sku).toUpperCase()===sku.toUpperCase());data=p?[p]:[]}if(error)return toast(error.message);if(data?.length)addProduct(data[0]);else if(confirm(`SKU no encontrado: ${sku}\n¿Crear manualmente?`))openManual(sku)},()=>{}).catch(e=>$('#reader').innerHTML=`<div class="errorbox">No se pudo abrir la cámara: ${esc(e)}</div>`)}
$('#scanBtn').onclick=openScanner;$('#fabScan').onclick=openScanner;

function orderPayload(){return {p_cliente_id:client?.id||null,p_cliente_nombre:client?.razon_social||'Cliente sin identificar',p_forma_pago:$('#payment').value,p_descuento_pct:Number($('#discount').value||0),p_observaciones:$('#obs').value.trim()||null,p_offline_id:crypto.randomUUID(),p_items:cart.map(x=>({sku:x.sku,cantidad:Number(x.qty),precio:Number(x.precio),descripcion:x.descripcion,tipo:x.tipo,producto:x.producto,color:x.color,medida:x.medida,unidad_venta:x.unidad_venta,observacion_item:x.observacion_item||null})),p_modalidad_entrega:$('#delivery').value,p_transporte:$('#delivery').value==='Transporte'?($('#transport').value.trim()||null):null}}
function summaryHtml(){const s=cart.reduce((a,x)=>a+x.qty*Number(x.precio),0),p=Math.min(30,Math.max(0,Number($('#discount').value||0))),d=s*p/100,n=s-d,iv=n*.21,miss=missingClient(client);return `<div class="copy-card"><div class="copy-title">Confirmación de pedido Adhome</div><div class="meta">Cliente: ${esc(client?.razon_social||'Sin cliente')}</div><div class="order-lines">${cart.map(x=>`<div class="order-line"><div><b>${esc(x.descripcion)}</b><div class="meta">${esc(x.sku)}</div></div><div>${x.qty} u.</div><div class="right">${money(x.qty*x.precio)}</div></div>`).join('')}</div><div class="totals"><div><span>Subtotal s/IVA</span><b>${money(s)}</b></div><div><span>Descuento ${p}%</span><b>${money(d)}</b></div><div><span>Neto s/IVA</span><b>${money(n)}</b></div><div><span>IVA 21%</span><b>${money(iv)}</b></div><div class="grand"><span>Total c/IVA</span><b>${money(n+iv)}</b></div></div><div class="meta">Pago: ${esc($('#payment').value)} · Entrega: ${esc($('#delivery').value)}${$('#delivery').value==='Transporte'?' · '+esc($('#transport').value):''}</div>${$('#obs').value?`<div style="margin-top:8px"><b>Observaciones:</b> ${esc($('#obs').value)}</div>`:''}${miss.length?`<div class="warn tiny">Datos de cliente incompletos: ${miss.join(', ')}. No bloquea.</div>`:''}${cart.reduce((a,x)=>a+x.qty,0)<60?'<div class="warn tiny">Pedido menor a 60 unidades. No bloquea.</div>':''}</div><button id="doConfirm" class="btn primary big" style="width:100%;margin-top:12px">Confirmar pedido</button>`}
$('#confirm').onclick=()=>{if(!cart.length)return toast('Agregá al menos un artículo');if($('#delivery').value==='Transporte'&&!$('#transport').value.trim())return toast('Indicá el transporte');modal('Revisar pedido',summaryHtml());$('#doConfirm').onclick=confirmOrder};
async function confirmOrder(){const payload=orderPayload();$('#doConfirm').disabled=true;$('#doConfirm').textContent='Confirmando...';try{if(!navigator.onLine)throw Error('OFFLINE');const {data,error}=await sb.rpc('confirmar_pedido',payload);if(error)throw error;closeModal();await afterConfirmed(data)}catch(e){if(e.message==='OFFLINE'||/fetch/i.test(e.message||'')){const q=pendingQueue();q.push({created_at:new Date().toISOString(),payload});saveQueue(q);closeModal();toast('Pedido guardado en este dispositivo. Se sincronizará automáticamente al volver Internet.');resetOrder()}else{toast(e.message);$('#doConfirm').disabled=false;$('#doConfirm').textContent='Confirmar pedido'}}}
async function afterConfirmed(id){await Promise.all([loadOrders(),loadDash(),loadProducts('')]);const o=lastOrders.find(x=>x.id===id)||(await sb.from('pedidos').select('*,pedido_items(*)').eq('id',id).single()).data;resetOrder();if(o)openOrder(o,true)}
function resetOrder(){cart=[];client=null;$('#obs').value='';$('#discount').value=0;$('#transport').value='';$('#delivery').value='Retiro en fábrica';$('#payment').value='Transferencia bancaria';clearDraft();renderClient();renderCart();toggleTransport()}
async function loadOrders(){const {data,error}=await sb.from('pedidos').select('*,pedido_items(*)').order('created_at',{ascending:false}).limit(300);if(error){$('#orders').innerHTML=`<div class="errorbox">${esc(error.message)}</div>`;return}lastOrders=data||[];renderOrders()}
function renderOrders(){const q=($('#osearch').value||'').trim().toLowerCase();const arr=lastOrders.filter(o=>!q||String(o.numero).includes(q)||String(o.cliente_nombre_snapshot||'').toLowerCase().includes(q)||String(o.vendedor_nombre_snapshot||'').toLowerCase().includes(q));$('#orders').innerHTML=arr.map(o=>`<div class="order" data-oid="${o.id}"><div class="row"><div><b>Pedido ${o.numero}</b><div class="meta">${esc(o.cliente_nombre_snapshot||'Sin cliente')} · ${esc(o.vendedor_nombre_snapshot||'')} · ${new Date(o.created_at).toLocaleString('es-AR')}</div></div><div class="right"><b>${money(o.neto_sin_iva)}</b><div class="mini muted">s/IVA</div></div></div><div class="meta">${o.unidades} u.${o.unidades_pendientes?` · <span style="color:#b54708">${o.unidades_pendientes} pendientes</span>`:''} · ${esc(o.forma_pago||'')} · ${esc(o.modalidad_entrega||'')}</div></div>`).join('')||'<div class="muted">Sin pedidos.</div>'}
$('#refreshOrders').onclick=loadOrders;$('#osearch').oninput=renderOrders;$('#orders').onclick=e=>{const x=e.target.closest('[data-oid]');if(!x)return;const o=lastOrders.find(z=>z.id===x.dataset.oid);if(o)openOrder(o,false)};
function customerText(o){const lines=(o.pedido_items||[]).map(i=>`${i.cantidad} x ${i.descripcion_snapshot} (${i.sku}) · ${money(i.precio_unitario)} c/u`).join('\n');return `Confirmación de pedido Adhome\nPedido ${o.numero}\nFecha: ${new Date(o.created_at).toLocaleString('es-AR')}\nCliente: ${o.cliente_nombre_snapshot||'Sin cliente'}\nVendedor: ${o.vendedor_nombre_snapshot||''}\n\n${lines}\n\nSubtotal s/IVA: ${money(o.subtotal_sin_iva)}\nDescuento ${Number(o.descuento_pct||0)}%: ${money(o.descuento_importe)}\nNeto s/IVA: ${money(o.neto_sin_iva)}\nIVA 21%: ${money(o.iva_importe)}\nTotal c/IVA: ${money(o.total_con_iva)}\nPago: ${o.forma_pago||''}\nEntrega: ${o.modalidad_entrega||''}${o.transporte_snapshot?' · '+o.transporte_snapshot:''}${o.observaciones?'\nObservaciones: '+o.observaciones:''}`}
