const SUPA_URL='https://uakqtfggbiicmutifqrj.supabase.co';
const SUPA_KEY='sb_publishable_5owhbnD1dTCUjaFSFcJC0A_Akgxxgzl';
const REGISTER_URL=SUPA_URL+'/functions/v1/presentes-register';
const sb=window.supabase.createClient(SUPA_URL,SUPA_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
let session=null, profile=null, client=null, cart=[], lastOrders=[], realtime=null, draftTimer=null;
let productCache=JSON.parse(localStorage.getItem('presentes_products')||'[]'), clientCache=JSON.parse(localStorage.getItem('presentes_clients')||'[]');
const appUrl=()=>location.origin+location.pathname.replace(/\/$/,'');
function toast(t){alert(t)}
function modal(t,b){$('#mtitle').textContent=t;$('#mbody').innerHTML=b;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden');$('#mbody').innerHTML=''}
$('#mclose').onclick=closeModal;
function setSync(text,cls=''){$('#syncState').textContent=text;$('#syncState').className='sync '+cls}
function missingClient(c){if(!c)return ['cliente'];return ['cuit','telefono','email','localidad','provincia','condicion_fiscal','domicilio_entrega','transporte'].filter(k=>!c[k])}
function draftData(){return {client,cart,payment:$('#payment')?.value,delivery:$('#delivery')?.value,transport:$('#transport')?.value,discount:$('#discount')?.value,obs:$('#obs')?.value}}
function saveDraft(){if(!$('#app')||$('#app').classList.contains('hidden'))return;clearTimeout(draftTimer);draftTimer=setTimeout(()=>localStorage.setItem('presentes_draft',JSON.stringify(draftData())),100)}
function clearDraft(){localStorage.removeItem('presentes_draft')}
function restoreDraft(){try{const d=JSON.parse(localStorage.getItem('presentes_draft')||'null');if(!d)return;client=d.client||null;cart=Array.isArray(d.cart)?d.cart:[];$('#payment').value=d.payment||'Transferencia bancaria';$('#delivery').value=d.delivery||'Retiro en fábrica';$('#transport').value=d.transport||'';$('#discount').value=d.discount||0;$('#obs').value=d.obs||'';renderClient();renderCart();toggleTransport()}catch{}}
function pendingQueue(){try{return JSON.parse(localStorage.getItem('presentes_pending')||'[]')}catch{return []}}
function saveQueue(q){localStorage.setItem('presentes_pending',JSON.stringify(q));setSync(q.length?`${q.length} pedido/s pendiente/s de sincronizar`:'Sincronizado',q.length?'pending':'ok')}
async function syncQueue(){if(!navigator.onLine||!session)return;let q=pendingQueue();if(!q.length){setSync('Sincronizado','ok');return}setSync(`Sincronizando ${q.length}...`,'pending');const remain=[];for(const x of q){try{const {error}=await sb.rpc('confirmar_pedido',x.payload);if(error)throw error}catch(e){remain.push(x)}}saveQueue(remain);if(!remain.length){await loadOrders();await loadDash();await loadProducts('')}}
async function login(){const email=$('#lemail').value.trim(),password=$('#lpass').value;$('#loginMsg').textContent='';if(!email||password.length<6){$('#loginMsg').textContent='Ingresá email y contraseña.';return}const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){$('#loginMsg').textContent=error.message;return}session=data.session;await startApp()}
async function firstAccess(){const email=$('#lemail').value.trim(),password=$('#lpass').value;$('#loginMsg').textContent='';if(!email||password.length<6){$('#loginMsg').textContent='Ingresá tu email autorizado y elegí una contraseña de al menos 6 caracteres.';return}$('#firstBtn').disabled=true;try{const r=await fetch(REGISTER_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw Error(d.error||'No se pudo crear el acceso');$('#loginMsg').textContent=d.message||'Usuario creado. Ingresando...';await sleep(250);await login()}catch(e){$('#loginMsg').textContent=e.message}finally{$('#firstBtn').disabled=false}}
$('#loginBtn').onclick=login;$('#firstBtn').onclick=firstAccess;$('#lpass').addEventListener('keydown',e=>{if(e.key==='Enter')login()});
$('#logout').onclick=async()=>{await sb.auth.signOut();location.reload()};
async function startApp(){const {data:{session:s}}=await sb.auth.getSession();session=s;if(!session){$('#login').classList.remove('hidden');$('#app').classList.add('hidden');return}let p=null;if(navigator.onLine){const r=await sb.from('profiles').select('*').eq('id',session.user.id).single();if(r.error||!r.data||!r.data.active){await sb.auth.signOut();$('#loginMsg').textContent='Usuario no habilitado o inactivo.';return}p=r.data;localStorage.setItem('presentes_profile',JSON.stringify(p))}else{p=JSON.parse(localStorage.getItem('presentes_profile')||'null');if(!p){$('#loginMsg').textContent='Primero ingresá una vez con conexión para habilitar el modo offline.';return}}profile=p;$('#topUser').textContent=p.full_name||p.email;$('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#adminNav').classList.toggle('hidden',p.role!=='admin');$('#adminOnly').classList.toggle('hidden',p.role!=='admin');restoreDraft();if(navigator.onLine){await Promise.all([cacheMasters(),loadProducts(''),loadClients(''),loadOrders(),loadDash()]);if(profile.role==='admin')await loadAdmin();setupRealtime();syncQueue()}else{setSync('Sin conexión · modo offline','pending');await loadProducts('');await loadClients('')}}

function debounce(fn,ms=250){let t;return (...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}}
async function cacheMasters(){try{const [pr,cr]=await Promise.all([sb.from('productos').select('*').eq('activo',true).order('descripcion').limit(1000),sb.from('clientes').select('*').eq('activo',true).order('razon_social').limit(2000)]);if(!pr.error){productCache=pr.data||[];localStorage.setItem('presentes_products',JSON.stringify(productCache))}if(!cr.error){clientCache=cr.data||[];localStorage.setItem('presentes_clients',JSON.stringify(clientCache))}}catch{}}
async function loadProducts(q=''){let data=[],error=null;if(!navigator.onLine){const z=q.toLowerCase();data=productCache.filter(p=>!z||[p.sku,p.descripcion,p.producto,p.color,p.medida].some(v=>String(v||'').toLowerCase().includes(z))).slice(0,60)}else{let query=sb.from('productos').select('*').eq('activo',true).order('descripcion').limit(60);if(q)query=query.or(`sku.ilike.%${q}%,descripcion.ilike.%${q}%,producto.ilike.%${q}%,color.ilike.%${q}%`);const r=await query;data=r.data||[];error=r.error}if(error){$('#presults').innerHTML=`<div class="errorbox tiny">${esc(error.message)}</div>`;return}$('#presults').innerHTML=(data||[]).map(p=>`<div class="result" data-sku="${esc(p.sku)}"><b>${esc(p.descripcion)}</b><div class="meta">${esc(p.sku)} · ${money(p.precio)} + IVA · Stock <span class="${p.stock_disponible>0?'stockok':'stock0'}">${p.stock_disponible}</span></div></div>`).join('')}
$('#psearch').oninput=debounce(e=>loadProducts(e.target.value.trim()));
$('#presults').onclick=async e=>{const x=e.target.closest('[data-sku]');if(!x)return;let data;if(navigator.onLine){data=(await sb.from('productos').select('*').eq('sku',x.dataset.sku).single()).data}else data=productCache.find(p=>p.sku===x.dataset.sku);if(data)addProduct(data)};
async function loadClients(q=''){let data=[],error=null;if(!navigator.onLine){const z=q.toLowerCase();data=clientCache.filter(c=>!z||[c.razon_social,c.codigo,c.cuit,c.email,c.telefono].some(v=>String(v||'').toLowerCase().includes(z))).slice(0,50)}else{let query=sb.from('clientes').select('*').eq('activo',true).order('razon_social').limit(50);if(q)query=query.or(`razon_social.ilike.%${q}%,codigo.ilike.%${q}%,cuit.ilike.%${q}%,email.ilike.%${q}%,telefono.ilike.%${q}%`);const r=await query;data=r.data||[];error=r.error}if(error){$('#cresults').innerHTML=`<div class="errorbox tiny">${esc(error.message)}</div>`;return}$('#cresults').innerHTML=(data||[]).map(c=>`<div class="result" data-cid="${c.id}"><b>${esc(c.razon_social)}</b><div class="meta">${esc(c.codigo||'')} ${c.cuit?'· CUIT '+esc(c.cuit):''}</div></div>`).join('')}
$('#csearch').oninput=debounce(e=>loadClients(e.target.value.trim()));
$('#cresults').onclick=async e=>{const x=e.target.closest('[data-cid]');if(!x)return;let data;if(navigator.onLine){data=(await sb.from('clientes').select('*').eq('id',x.dataset.cid).single()).data}else data=clientCache.find(c=>c.id===x.dataset.cid);client=data;$('#csearch').value='';$('#cresults').innerHTML='';renderClient();saveDraft()};
$('#clearClient').onclick=()=>{client=null;renderClient();saveDraft()};
function renderClient(){if(!client){$('#cselected').innerHTML='<div class="warn tiny">Sin cliente seleccionado. Se puede confirmar igualmente.</div>';return}const miss=missingClient(client);$('#cselected').innerHTML=`<div class="${miss.length?'warn':'okbox'}"><b>${esc(client.razon_social)}</b><div class="tiny">${client.cuit?'CUIT '+esc(client.cuit):''}</div>${miss.length?`<div class="tiny">Faltan: ${miss.join(', ')}. No bloquea el pedido.</div>`:''}<button id="editClient" class="btn" style="margin-top:7px">Completar / editar</button></div>`;$('#editClient').onclick=()=>clientForm(client)}
function clientForm(c=null){modal(c?'Editar cliente':'Cliente nuevo',`<div class="grid2"><input id="fn" placeholder="Razón social / Nombre" value="${esc(c?.razon_social||'')}"><input id="fcuit" placeholder="CUIT" value="${esc(c?.cuit||'')}"><input id="ftel" placeholder="Teléfono" value="${esc(c?.telefono||'')}"><input id="femail" placeholder="Email" value="${esc(c?.email||'')}"><input id="floc" placeholder="Localidad" value="${esc(c?.localidad||'')}"><input id="fprov" placeholder="Provincia" value="${esc(c?.provincia||'')}"><input id="ffisc" placeholder="Condición fiscal" value="${esc(c?.condicion_fiscal||'')}"><input id="fdom" placeholder="Domicilio fiscal" value="${esc(c?.domicilio||'')}"><input id="fent" placeholder="Domicilio entrega" value="${esc(c?.domicilio_entrega||'')}"><input id="ftrans" placeholder="Transporte" value="${esc(c?.transporte||'')}"></div><button id="saveClient" class="btn primary">Guardar y usar</button>`);$('#saveClient').onclick=async()=>{const body={razon_social:$('#fn').value.trim()||'Cliente sin nombre',cuit:$('#fcuit').value.trim()||null,telefono:$('#ftel').value.trim()||null,email:$('#femail').value.trim()||null,localidad:$('#floc').value.trim()||null,provincia:$('#fprov').value.trim()||null,condicion_fiscal:$('#ffisc').value.trim()||null,domicilio:$('#fdom').value.trim()||null,domicilio_entrega:$('#fent').value.trim()||null,transporte:$('#ftrans').value.trim()||null,activo:true};let res;if(c)res=await sb.from('clientes').update(body).eq('id',c.id).select().single();else res=await sb.from('clientes').insert({...body,creado_en_feria:true}).select().single();if(res.error)return toast(res.error.message);client=res.data;closeModal();renderClient();saveDraft();loadClients('')}}
$('#newClient').onclick=()=>clientForm(null);

function addProduct(p){const ex=cart.find(x=>String(x.sku).toUpperCase()===String(p.sku).toUpperCase());if(ex)ex.qty+=1;else cart.push({...p,qty:1,observacion_item:p.observacion_manual||''});renderCart();$('#psearch').value='';$('#presults').innerHTML='';saveDraft();setTimeout(()=>{const i=cart.findIndex(x=>x.sku===p.sku);const q=document.querySelector(`[data-qty="${i}"]`);if(q){q.focus();q.select()}},30)}
