function orderCopyHtml(o){return `<div class="copy-card"><img class="copy-logo" src="./logo.png" alt="ADHOME"><div class="copy-title">Confirmación de pedido Adhome</div><div class="meta">Pedido ${o.numero} · ${new Date(o.created_at).toLocaleString('es-AR')}</div><div style="margin-top:9px"><b>Cliente:</b> ${esc(o.cliente_nombre_snapshot||'Sin cliente')}<br><b>Vendedor:</b> ${esc(o.vendedor_nombre_snapshot||'')}</div><div class="order-lines">${(o.pedido_items||[]).map(i=>`<div class="order-line"><div><b>${esc(i.descripcion_snapshot)}</b><div class="meta">${esc(i.sku)}${i.observacion_item?' · '+esc(i.observacion_item):''}</div></div><div>${i.cantidad} u.</div><div class="right">${money(i.cantidad*Number(i.precio_unitario))}</div></div>`).join('')}</div><div class="totals"><div><span>Subtotal s/IVA</span><b>${money(o.subtotal_sin_iva)}</b></div><div><span>Descuento ${Number(o.descuento_pct||0)}%</span><b>${money(o.descuento_importe)}</b></div><div><span>Neto s/IVA</span><b>${money(o.neto_sin_iva)}</b></div><div><span>IVA 21%</span><b>${money(o.iva_importe)}</b></div><div class="grand"><span>Total c/IVA</span><b>${money(o.total_con_iva)}</b></div></div><div class="meta" style="margin-top:8px"><b>Pago:</b> ${esc(o.forma_pago||'')} · <b>Entrega:</b> ${esc(o.modalidad_entrega||'')}${o.transporte_snapshot?' · '+esc(o.transporte_snapshot):''}</div>${o.observaciones?`<div style="margin-top:8px"><b>Observaciones:</b> ${esc(o.observaciones)}</div>`:''}</div>`}
function openOrder(o,justConfirmed=false){modal(justConfirmed?'Pedido confirmado':'Detalle de pedido',`${orderCopyHtml(o)}${o.unidades_pendientes?`<div class="warn tiny no-print">Interno: ${o.unidades_pendientes} unidad/es pendientes por stock. Este dato no se incluye al compartir con el cliente.</div>`:''}<div class="share-row no-print" style="margin-top:12px"><button id="ow" class="btn">WhatsApp</button><button id="oe" class="btn">Email</button><button id="oc" class="btn">Copiar</button><button id="op" class="btn">Imprimir / PDF</button></div>`);const txt=customerText(o);$('#ow').onclick=()=>window.open('https://wa.me/?text='+encodeURIComponent(txt),'_blank');$('#oe').onclick=()=>location.href=`mailto:?subject=${encodeURIComponent('Confirmación de pedido Adhome - Pedido '+o.numero)}&body=${encodeURIComponent(txt)}`;$('#oc').onclick=async()=>{await navigator.clipboard.writeText(txt);toast('Copiado')};$('#op').onclick=()=>{const p=$('#printArea');p.innerHTML=orderCopyHtml(o);p.classList.remove('hidden');window.print();p.classList.add('hidden')}}

function pctBar(label,val,max,fmt=v=>String(v)){return `<div class="barrow"><div class="tiny">${esc(label)}</div><div class="bar"><i style="width:${max?Math.max(2,Math.round(val/max*100)):0}%"></i></div><div class="tiny right">${fmt(val)}</div></div>`}
async function loadDash(){const {data,error}=await sb.from('pedidos').select('*,pedido_items(*)').eq('estado','CONFIRMADO').order('created_at',{ascending:false}).limit(1200);if(error)return;const a=data||[],sales=a.reduce((s,o)=>s+Number(o.neto_sin_iva||0),0),units=a.reduce((s,o)=>s+Number(o.unidades||0),0),pending=a.reduce((s,o)=>s+Number(o.unidades_pendientes||0),0),clients=new Set(a.map(o=>o.cliente_id).filter(Boolean)).size;$('#ksales').textContent=money(sales);$('#korders').textContent=a.length;$('#kclients').textContent=clients;$('#kticket').textContent=money(a.length?sales/a.length:0);$('#kunits').textContent=units;$('#kpending').textContent=pending;
 const sellers={};a.forEach(o=>sellers[o.vendedor_nombre_snapshot||'Sin vendedor']=(sellers[o.vendedor_nombre_snapshot||'Sin vendedor']||0)+Number(o.neto_sin_iva||0));const sellerArr=Object.entries(sellers).sort((x,y)=>y[1]-x[1]);const maxSeller=sellerArr[0]?.[1]||0;$('#bySeller').innerHTML=sellerArr.map(([k,v])=>pctBar(k,v,maxSeller,money)).join('')||'<div class="muted tiny">Sin ventas.</div>';
 const hours={};const now=new Date();a.forEach(o=>{const d=new Date(o.created_at);if(d.toLocaleDateString('es-AR')===now.toLocaleDateString('es-AR')){const h=String(d.getHours()).padStart(2,'0')+':00';hours[h]=(hours[h]||0)+Number(o.neto_sin_iva||0)}});const hArr=Object.entries(hours).sort((a,b)=>a[0].localeCompare(b[0])),maxH=Math.max(0,...hArr.map(x=>x[1]));$('#byHour').innerHTML=hArr.map(([k,v])=>pctBar(k,v,maxH,money)).join('')||'<div class="muted tiny">Sin ventas hoy.</div>';
 const prods={},cats={};a.forEach(o=>(o.pedido_items||[]).forEach(i=>{const factor=1-Number(o.descuento_pct||0)/100,net=Number(i.subtotal||0)*factor;const pk=i.descripcion_snapshot||i.sku;prods[pk]??={u:0,v:0};prods[pk].u+=Number(i.cantidad||0);prods[pk].v+=net;const ck=i.tipo_snapshot||'Sin categoría';cats[ck]=(cats[ck]||0)+net}));$('#topProducts').innerHTML=Object.entries(prods).sort((a,b)=>b[1].v-a[1].v).slice(0,10).map(([k,v])=>`<div class="result"><b>${esc(k)}</b><div class="meta">${v.u} u. · ${money(v.v)} s/IVA</div></div>`).join('')||'<div class="muted tiny">Sin datos.</div>';$('#topCats').innerHTML=Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([k,v])=>`<div class="result"><b>${esc(k)}</b><div class="meta">${money(v)} s/IVA</div></div>`).join('')||'<div class="muted tiny">Sin datos.</div>';$('#recent').innerHTML=a.slice(0,12).map(o=>`<div class="result"><b>Pedido ${o.numero} · ${money(o.neto_sin_iva)}</b><div class="meta">${esc(o.cliente_nombre_snapshot||'Sin cliente')} · ${esc(o.vendedor_nombre_snapshot||'')}</div></div>`).join('')||'<div class="muted tiny">Sin pedidos.</div>'}

async function loadAdmin(){if(profile?.role!=='admin')return;const [{data:allowed},{data:profiles},{data:audit}]=await Promise.all([sb.from('allowed_users').select('*').order('full_name'),sb.from('profiles').select('*'),sb.from('audit_log').select('*').order('created_at',{ascending:false}).limit(50)]);const activeEmails=new Set((profiles||[]).map(x=>String(x.email||'').toLowerCase()));$('#usersList').innerHTML=(allowed||[]).map(u=>`<div class="admin-user"><div><b>${esc(u.full_name)}</b><div class="meta">${esc(u.email)} · ${u.role==='admin'?'Administrador':'Vendedor'} · ${activeEmails.has(u.email.toLowerCase())?'Acceso creado':'Pendiente de crear acceso'} · ${u.active?'Activo':'Inactivo'}</div></div><button class="btn ${u.active?'danger':'good'}" data-usr="${esc(u.email)}" data-active="${u.active?'0':'1'}">${u.active?'Desactivar':'Activar'}</button></div>`).join('');$('#audit').innerHTML=(audit||[]).map(a=>`<div class="result"><b>${esc(a.action)}</b><div class="meta">${esc(a.actor_name||'Sistema')} · ${esc(a.entity)} ${esc(a.entity_id||'')} · ${new Date(a.created_at).toLocaleString('es-AR')}</div></div>`).join('')||'<div class="muted tiny">Sin movimientos.</div>'}
$('#inviteUser').onclick=async()=>{const email=$('#uemail').value.trim().toLowerCase(),name=$('#uname').value.trim(),phone=$('#uphone').value.trim()||null,role=$('#urole').value;if(!email||!name)return toast('Completá email y nombre');const {data,error}=await sb.rpc('invitar_usuario',{p_email:email,p_full_name:name,p_phone:phone,p_role:role});if(error)return toast(error.message);const text=`ADHOME PRESENTES 2026\nFuiste habilitado para ingresar.\nAbrí: ${appUrl()}\nUsá tu email ${email} y tocá “Primera vez / Crear acceso” para elegir tu contraseña.`;$('#inviteResult').innerHTML=`<div class="okbox tiny"><b>${esc(name)}</b> habilitado.<div class="share-row" style="margin-top:8px"><button id="icopy" class="btn">Copiar invitación</button><button id="imail" class="btn">Email</button><button id="iwa" class="btn">WhatsApp</button></div></div>`;$('#icopy').onclick=async()=>{await navigator.clipboard.writeText(text);toast('Invitación copiada')};$('#imail').onclick=()=>location.href=`mailto:${encodeURIComponent(email)}?subject=${encodeURIComponent('Acceso ADHOME PRESENTES 2026')}&body=${encodeURIComponent(text)}`;$('#iwa').onclick=()=>window.open('https://wa.me/?text='+encodeURIComponent(text),'_blank');$('#uemail').value='';$('#uname').value='';$('#uphone').value='';await loadAdmin()};
$('#usersList').onclick=async e=>{const b=e.target.closest('[data-usr]');if(!b)return;const active=b.dataset.active==='1';if(!confirm(`${active?'Activar':'Desactivar'} ${b.dataset.usr}?`))return;const {error}=await sb.rpc('set_usuario_activo',{p_email:b.dataset.usr,p_active:active});if(error)return toast(error.message);loadAdmin()};
$('#adjustStock').onclick=async()=>{const sku=$('#asku').value.trim(),qty=Number($('#aqty').value||0),reason=$('#areason').value.trim()||null;if(!sku||!qty)return toast('Ingresá SKU y cantidad distinta de 0');const {data,error}=await sb.rpc('ajustar_stock',{p_sku:sku,p_cantidad:qty,p_tipo:qty>0?'REPOSICION':'AJUSTE',p_motivo:reason});if(error)return $('#aresult').textContent=error.message;$('#aresult').textContent=`${data.descripcion}: stock ${data.stock_disponible}`;loadProducts('');loadAdmin()};
$('#loadProdAdmin').onclick=async()=>{const sku=$('#pskuAdmin').value.trim();const {data,error}=await sb.from('productos').select('*').eq('sku',sku).maybeSingle();if(error||!data)return $('#prodAdmin').innerHTML='<div class="errorbox tiny">SKU no encontrado.</div>';$('#prodAdmin').innerHTML=`<input id="apdesc" value="${esc(data.descripcion)}"><input id="apprice" type="number" value="${Number(data.precio)}"><label class="tiny"><input id="apactive" type="checkbox" ${data.activo?'checked':''} style="width:auto;margin-right:6px">Activo</label><button id="apsave" class="btn primary">Guardar producto</button>`;$('#apsave').onclick=async()=>{const {error}=await sb.rpc('actualizar_producto_admin',{p_sku:data.sku,p_precio:Number($('#apprice').value),p_descripcion:$('#apdesc').value.trim(),p_activo:$('#apactive').checked});if(error)return toast(error.message);toast('Producto actualizado');loadProducts('');loadAdmin()}};

function setupRealtime(){if(realtime)return;realtime=sb.channel('presentes-live').on('postgres_changes',{event:'*',schema:'public',table:'pedidos'},debounce(()=>{loadOrders();loadDash()},350)).on('postgres_changes',{event:'UPDATE',schema:'public',table:'productos'},debounce(()=>loadProducts($('#psearch').value.trim()),350)).subscribe()}
$$('.nav button').forEach(b=>b.onclick=()=>{$$('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.v).classList.add('active');if(b.dataset.v==='pedidos')loadOrders();if(b.dataset.v==='dash')loadDash();if(b.dataset.v==='admin')loadAdmin()});
window.addEventListener('online',()=>{setSync('Reconectando...','pending');syncQueue()});window.addEventListener('offline',()=>setSync('Sin conexión · pedidos se guardan localmente','pending'));
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
renderClient();renderCart();toggleTransport();
sb.auth.onAuthStateChange((event,s)=>{session=s;if(event==='SIGNED_OUT'){profile=null;$('#app').classList.add('hidden');$('#login').classList.remove('hidden')}});
startApp();
